### ISSUE TITLE
Find the source of crashes in the live system

### ISSUE THREAD

**Issue by Geod24** [bpfkorea/faucet#13]
Currently, we have a [workaround](https://github.com/bpfkorea/faucet/pull/11) in place to work around a weird behavior observed in the live system: an `assert` which should only be triggered far into the future by our calculation fires after roughly 100 transactions. That's very unexpected, and a sign that something else is wrong.

We need to find why it actually asserts (how do we end up with a `0` output), if it makes sense, and eventually fix it.

**Comment by kchulj** [comment]
From the discussion yesterday:
The `leftover` in the `TxBuilder` acts as a "bank"  to distribute the `Amount` among the addresses. If there is a remainder, the remainder also becomes an `Output`. The `Amount` of this remainder is often a single or double digit number. 

This pattern will create such a transaction:
```
[main(aPGx) INF] Transaction sent: 
Transaction(Payment [Input(0xf423797f996b6575964b144492a8256d632f4a3f292aac90f508e6c717bfc80201c2d63fc5ea959e5d2e752054df3ca40b78143181c672345acf61259e0fe1d3, 0x071a55ddd72bb1663bb2f79d229eeabd6a359efc59d63fea5487c52a68b46ca1b988239e3b3ac8df4a94b911ca79f68f0b3d425179948540694f70decff97e7f)],
[Output(1, GDAXQ22NNR5QY4QE6FCO3LNGESAB445WGA3FLGFJJZ62DONIKNLVIBNY),
Output(1, GDAXR22XD5NZAGEOBDA3RHIUADXOJOI2GOI26AB5DO3RPH23ITXMRY22),
Output(1, GDAXS22JTAFEBED5DCNL7LAAJTOF6GOSOZAZASM6JGRNWUJM7HFMJRUE),
Output(1, GDAXT22T25MN4MR7DA5MPMLSWMSTXBAV2ANGKUN2ZYPEB4LLMVWXTNIU),
Output(1, GDAXU22S3PUB33SFHSTZPBESQJWEPTZBMJ6ENTCTLMOKEE52435UZDSJ),
Output(1, GDAXV227S53ZCTS2ZH22GEYOXCC2BD2LLCSC2UDQYJ7I4P4MQD52YITQ),
Output(1, GDAXW22VOJALVR5C7H5S4AA422U6NZ2WDBGQJVIFVMCOAOL6JB2NAHMC),
Output(1, GDAXX22G3XSNAFGLE667H4TFHFZGL6YOQONBY63OID6COHGA5QWIYFVD),
Output(1, GDAXY22P7WT4YIYUVUJE62VIX5MCAWDSMF2OMPGUTTEP2RDYTNERIUR3),
Output(1, GDAXZ22F2W5GSGAQVDF6PHXF2POEZS4SPKY6OY4AQXNZI26JPG5NA4RX),
Output(1, GDAYA22E7REHMIJWM5ZJMMWL6NOEFQDMKRGEODJK53S65APMKXPPGDAO),
Output(1, GDAYB225FANP44PWDRL4DIKWBLWI3XKB7HCI6ZM3IBRHKVOKNA3JINOK),
Output(1, GDAYC22J6MMZLC3UQAVDLHNK3GMQT3AXE37HEGNQQZ7YPDY4HYNPAAOR),
Output(1, GDAYD22AI62J5LGNRTCGFSMNWL6C4QBFU45KAUZXCK5YSHUEMJ3N6XGW),
Output(1, GDAYE226OWBW6C55F4WKULJFUYMUFIOSTBARJX4Q23BLMB7X2M5UD2KM),
Output(1, GDAQM22JUNLMKPHVXTERSOLX7UPF7O4ZH37RIIWCF5ZPERUH2MPB2UDJ)])
```
where the `Output`s here will attempt to get divided.

Therefore, I'm thinking of merging `Outputs` if the number of `UTXO` is above a certain number, or `Amount` is below a certain number.

Fixing #14 may solve this issue.
