### ISSUE TITLE
Agora node stops receiving transactions

### ISSUE THREAD

**Issue by kchulj** [bpfkorea/faucet#19]
The `faucet` continuously sends transactions, but the `agora` node stops receiving them at some point.
This usually happens around mid-30 blocks.
It may be related to `combineCandidates`.

**Comment by AndrejMitrovic** [comment]
Are you sure it's a faucet bug and not an agora bug?

**Comment by kchulj** [comment]
It's an agora bug :)

**Comment by Geod24** [comment]
FYI you can transfer issues between repos ;)
